WebAdvert.Web/Models/Accounts/AuthResponseModel.cs
namespace WebAdvert.Web.Models.Accounts
{
    public class AuthResponseModel : BaseResponseModel
    {
        public string EmailAddress { get; set; }
        public string UserId { get; set; }
        public TokenModel Tokens { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/ConfirmForgotPasswordModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdvert.Web.Models.Accounts
{
    public class ConfirmForgotPasswordModel
    {
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "ConfirmationCode is required.")]
        [Display(Name = "ConfirmationCode")]
        public string ConfirmationCode { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/ForgotPasswordModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdvert.Web.Models.Accounts
{
    public class ForgotPasswordModel
    {
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/ForgotPasswordResponseModel.cs
namespace WebAdvert.Web.Models.Accounts
{
    public class ForgotPasswordResponseModel : BaseResponseModel
    {
    }
}

WebAdvert.Web/Models/Accounts/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdvert.Web.Models.Accounts
{
    public class LoginModel
    {
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/SignupModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdvert.Web.Models.Accounts
{
    public class SignupModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [StringLength(6, ErrorMessage = "password must be at least six characters long!")]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [StringLength(6, ErrorMessage = "password an its confirmation do not match!")]
        public string ConfirmPassword { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/TokenModel.cs
namespace WebAdvert.Web.Models.Accounts
{
    public class TokenModel
    {
        public string IdToken { get; set; }
        public string AccessToken { get; set; }
        public int ExpiresIn { get; set; }
        public string RefreshToken { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/UserConfirmSignUpModel.cs
namespace WebAdvert.Web.Models.Accounts
{
    public class UserConfirmSignUpModel
    {
        public string ConfirmationCode { get; set; }
        public string EmailAddress { get; set; }
        public string UserId { get; set; }
    }
}

WebAdvert.Web/Models/Accounts/UserSignUpResponse.cs
namespace WebAdvert.Web.Models.Accounts
{
    public class UserSignUpResponse : BaseResponseModel
    {
        public string UserId { get; set; }
        public string EmailAddress { get; set; }
    }
}

WebAdvert.Web/Models/AdvertManagement/CreateAdvertViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAdvert.Web.Models.AdvertManagement
{
    public class CreateAdvertViewModel
    {
        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }
        public string Description { get; set; }

        [Required(ErrorMessage = " Price is required.")]
        [DataType(DataType.Currency)]
        public double Price { get; set; }
    }
}

WebAdvert.Web/Models/BaseResponseModel.cs
using WebAdvert.Web.Enum;

namespace WebAdvert.Web.Models
{
    public class BaseResponseModel
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public CognitoStatusCodes Status { get; set; }
    }
}

WebAdvert.Web/Models/ErrorViewModel.cs
namespace WebAdvert.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAdvert.Web/Models/WeatherForecast.cs
namespace WebAdvert.Web.Controllers
{
    public class WeatherForecast
    {
        public DateTime Date { get; set; }
        public int TemperatureC { get; set; }
        public string Summary { get; set; }
    }
}

WebAdvert.Web/Controllers/AdvertManagementController.cs
using Amazon.AspNetCore.Identity.Cognito;
using Amazon.Extensions.CognitoAuthentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAdvert.Web.Models.Accounts;
using WebAdvert.Web.Models.AdvertManagement;
using WebAdvert.Web.Repositories;
using WebAdvert.Web.ServiceClients;

namespace WebAdvert.Web.Controllers
{
    public class AdvertManagementController : Controller
    {
        private readonly IAdvertApiClient _advertApiClient;
        private readonly IFileUploader _fileUploader;
        public AdvertManagementController(IAdvertApiClient advertApiClient, IFileUploader fileUploader)
        {
            _fileUploader = fileUploader;
            _advertApiClient = advertApiClient;
        }
        public async Task<IActionResult> Signup()
        {
            var model = new SignupModel();
            return View(model);
        }

        public IActionResult Create(CreateAdvertViewModel model)
        {
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAdvertViewModel model, IFormFile imageFile)
        {
            if(ModelState.IsValid)
            {
                var id = "11111";

                // You must make a call to Advert Api, create the advertisement in the database and return Id

                var fileName = "";
                if (imageFile != null)
                {
                    fileName = !string.IsNullOrEmpty(imageFile.FileName) ? Path.GetFileName(imageFile.FileName) : id;

                }
            }
        }
    }
}

WebAdvert.Web/Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebAdvert.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}

WebAdvert.Web/Views/Accounts/ConfirmForgotPassword.cshtml
@model WebAdvert.Web.Models.Accounts.ConfirmForgotPasswordModel

@{
    var userId = TempData["UserId"];
    var email = TempData["EmailAddress"];
}

<div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-6">
        <div class="col-md-12">
            <form method="POST">
                <div class="form-group">
                    <label asp-for="Email" class="form-label">EmailAddress</label>
                    <input class="form-control" asp-for="Email" required>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmationCode" class="form-label">ConfirmationCode</label>
                    <input class="form-control" asp-for="ConfirmationCode" required>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="form-label">Password</label>
                    <input class="form-control" asp-for="Password" required>
                </div>
                <button class="btn btn-primary" type="submit">Complete Reset Password</button>
            </form>
        </div>
    </div>
</div>

WebAdvert.Web/Views/Accounts/ConfirmSignup.cshtml
@model WebAdvert.Web.Models.Accounts.UserConfirmSignUpModel

@{
    var userId = TempData["UserId"];
    var email = TempData["EmailAddress"];
}

<div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-6">
        <div class="col-md-12">
            <form method="POST">
                <input type="hidden" asp-for="UserId" value="@userId" />
                <div class="form-group">
                    <label asp-for="EmailAddress" class="form-label">EmailAddress</label>
                    <input class="form-control" asp-for="EmailAddress" value="@email" readonly>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmationCode" class="form-label">ConfirmationCode</label>
                    <input class="form-control" asp-for="ConfirmationCode" required>
                </div>
                <button class="btn btn-primary" type="submit">Complete Signup</button>
            </form>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <a asp-action="Login">Login</a>
                </div>
                <div class="col-md-6">
                    <a asp-action="ForgotPassword">Forgot Password?</a>
                </div>
            </div>
        </div>
    </div>
</div>

WebAdvert.Web/Views/Accounts/ForgotPassword.cshtml
@model WebAdvert.Web.Models.Accounts.ForgotPasswordModel

<div class="row">
    <div class="col-md-4">
        <h4>Enter email to get new password.</h4>
        <hr/>

        <form method="post" asp-controller="Accounts" asp-action="ForgotPassword">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit">Reset</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Accounts/Login.cshtml
@model WebAdvert.Web.Models.Accounts.LoginModel

<div class="row">
    <div class="col-md-4">
        <h4>Login using your email and password</h4>
        <h5>
            <a asp-controller="Accounts" asp-action="Signup">
                If you are not a member you can sign up here
            </a>
        </h5>
        <hr/>

        <form method="post" asp-controller="Accounts" asp-action="Login">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label asp-for="RememberMe"></label>
                    <input asp-for="RememberMe" />
                    @Html.DisplayName("Remember Me")
                </div>
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Accounts/Signup.cshtml
@model WebAdvert.Web.Models.Accounts.SignupModel

<div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-6">
        <div class="col-md-12">
            <form method="POST">
                <div class="form-group">
                    <label asp-for="Email" class="form-label">Email</label>
                    <input class="form-control" asp-for="Email" required>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="form-label">Password</label>
                    <input type="password" class="form-control" asp-for="Password" required>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="form-label">ConfirmPassword</label>
                    <input type="password" class="form-control" asp-for="ConfirmPassword" required>
                </div>
                <button class="btn btn-primary" type="submit">Signup</button>
            </form>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <a asp-action="Login">Login</a>
                </div>
                <div class="col-md-6">
                    <a asp-action="ForgotPassword">Forgot Password?</a>
                </div>
            </div>
        </div>
    </div>
</div>

WebAdvert.Web/Views/AdvertManagement/Create.cshtml
@model WebAdvert.Web.Models.AdvertManagement.CreateAdvertViewModel

<div class="row">
    <div class="col-md-6">
        <form asp-controller="AdvertManagement" asp-action="Create" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="file" name="imageFile" value="Upload an image" />
            </div>
            <button type="submit" class="btn-default btn">Create</button>
        </form>
    </div>
</div>

WebAdvert.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAdvert.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAdvert.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAdvert.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAdvert.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAdvert.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>